@startuml
class moteurJeu.Clavier {
+ boolean haut
+ void appuyerTouche(KeyEvent)
+ void relacherTouche(KeyEvent)
}
class moteurJeu.MoteurJeu {
- {static} double FPS
- {static} double dureeFPS
- {static} double WIDTH
- {static} double HEIGHT
- FrameStats frameStats
- {static} Jeu jeu
- {static} DessinJeu dessin
~ Clavier controle
+ {static} void launch(Jeu,DessinJeu)
+ {static} void setFPS(int)
+ {static} void setTaille(double,double)
+ void start(Stage)
- void startAnimation(Canvas)
}
interface moteurJeu.Jeu {
~ void update(double,Clavier)
~ void init()
~ boolean etreFini()
}
interface moteurJeu.DessinJeu {
~ void dessinerJeu(Jeu,Canvas)
}



@enduml