@startuml




Personnage <|-- Perso
CaseDeclencheur <|-- CaseFermeture
Monstre <|-- Fantome
CaseDeclencheur <|-- CaseOuverture
Jeu <|.. LabyJeu
DessinJeu <|.. LabyDessin
Intelligence <|.. Troll
Monstre <|-- Troll
CaseDeclencheur <|-- CasePiege
Intelligence <|.. Monstre
Personnage <|-- Monstre
@enduml